# Generated by Django 5.2.15 on 2026-09-23 01:44

from django.db import migrations, models


STATUS_MIGRATIONS = {
    "PENDING": "DRAFT",
    "IN_PROGRESS": "ACTIVE",
    "BLOCKED": "NEEDS_REVISION",
    "SUCCEEDED": "COMPLETED",
    "CANCELLED": "ARCHIVED",
}

STATUS_ROLLBACKS = {
    "DRAFT": "PENDING",
    "ACTIVE": "IN_PROGRESS",
    # WAITING_HUMAN has no Phase 0 equivalent; IN_PROGRESS is the safest
    # rollback projection for an unfinished human gate.
    "WAITING_HUMAN": "IN_PROGRESS",
    "NEEDS_REVISION": "BLOCKED",
    "COMPLETED": "SUCCEEDED",
    "ARCHIVED": "CANCELLED",
}


def migrate_node_statuses(apps, schema_editor):
    """Map Phase 0 projection states onto the Phase 1 state machine."""
    node = apps.get_model("db", "ResearchChainNode")
    for old_status, new_status in STATUS_MIGRATIONS.items():
        node.objects.filter(status=old_status).update(status=new_status)


def rollback_node_statuses(apps, schema_editor):
    """Restore the legacy Phase 0 projection states."""
    node = apps.get_model("db", "ResearchChainNode")
    for new_status, old_status in STATUS_ROLLBACKS.items():
        node.objects.filter(status=new_status).update(status=old_status)


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0151_research_agent_plugin'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchchainsnapshot',
            name='event_range',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='researchchainsnapshot',
            name='resources',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='researchchainnode',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('WAITING_HUMAN', 'Waiting human'), ('NEEDS_REVISION', 'Needs revision'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20),
        ),
        migrations.RunPython(migrate_node_statuses, rollback_node_statuses),
    ]
