# Generated by Django 5.2.15 on 2026-09-23 02:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0152_research_chain_phase1_state_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchchainevent',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='ResearchChainUpload',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('request_id', models.CharField(max_length=128, unique=True)),
                ('payload_hash', models.CharField(max_length=64)),
                ('external_upload_id', models.CharField(blank=True, default='', max_length=128)),
                ('knowledge_id', models.CharField(blank=True, default='', max_length=128)),
                ('knowledge_base_id', models.CharField(blank=True, default='', max_length=128)),
                ('task_id', models.CharField(blank=True, default='', max_length=128)),
                ('file_name', models.CharField(max_length=500)),
                ('file_type', models.CharField(max_length=16)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('file_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('DEGRADED', 'Degraded')], default='PENDING', max_length=16)),
                ('error_code', models.CharField(blank=True, default='', max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploads', to='db.researchchain')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_chain_uploads', to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploads', to='db.researchchainnode')),
                ('reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chain_uploads', to='db.researchexternalreference')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_chain_uploads', to='db.workspace')),
            ],
            options={
                'db_table': 'research_chain_uploads',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['chain', 'node', 'file_hash'], name='rsch_upload_scope_hash_idx'), models.Index(fields=['workspace', 'status'], name='rsch_upload_ws_status_idx')],
            },
        ),
    ]
