# Generated by Django 5.2.15 on 2026-09-23 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0153_research_chain_uploads'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchagentsession',
            name='assembly',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='researchagentsession',
            name='delegated_subject',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='researchagentsession',
            name='synlora_run_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='researchagentsession',
            name='synlora_session_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='researchcontextgrant',
            name='allowed_file_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='researchcontextgrant',
            name='allowed_knowledge_base_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='researchcontextgrant',
            name='allowed_plugins',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='researchcontextgrant',
            name='allowed_tools',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='researchcontextgrant',
            name='policy_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='researchcontextgrant',
            name='policy_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
