# Generated by Django 5.2.15 on 2026-09-23 03:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0154_research_agent_context_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchchainsnapshot',
            name='snapshot_type',
            field=models.CharField(choices=[('LITERATURE_REVIEW', 'Literature review'), ('EXPERIMENT_EXECUTION', 'Experiment execution'), ('EXPERIMENT_DATA', 'Experiment data'), ('ANALYSIS_RESULT', 'Analysis result'), ('PAPER_RESEARCH', 'Paper research'), ('PROCESS', 'Process')], default='PROCESS', max_length=32),
        ),
        migrations.CreateModel(
            name='ResearchAnalysisResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('method', models.CharField(max_length=255)),
                ('input_refs', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField()),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('quality', models.JSONField(blank=True, default=dict)),
                ('conclusion', models.TextField(blank=True, default='')),
                ('tool_version', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACCEPTED', 'Accepted')], default='DRAFT', max_length=16)),
                ('request_id', models.CharField(max_length=128, unique=True)),
                ('payload_hash', models.CharField(max_length=64)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analysis_results', to='db.researchchain')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analysis_results', to='db.researchchainnode')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_analysis_results', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_analysis_results', to='db.workspace')),
            ],
            options={
                'db_table': 'research_analysis_results',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['chain', 'node', 'status'], name='rsch_analysis_node_idx')],
            },
        ),
    ]
