# Generated by Django 5.2.15 on 2026-10-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0162_research_office_attachment_limits"),
    ]

    operations = [
        migrations.AddField(
            model_name="periodicreportsnapshot",
            name="image_manifest",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="reportattachment",
            name="kind",
            field=models.CharField(
                choices=[
                    ("IMAGE", "Image"),
                    ("PDF", "PDF"),
                    ("MARKDOWN", "Markdown"),
                    ("OFFICE", "Office document"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=16,
            ),
        ),
    ]
