# Generated by Django 5.2.15 on 2026-10-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0163_report_image_snapshots"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchcontextgrant",
            name="allowed_reports",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
