# Generated by Django 5.2.15 on 2026-10-08 09:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0164_formal_report_context"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResearchFeedback",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[("bug", "Bug"), ("ux", "User experience"), ("idea", "Idea"), ("other", "Other")],
                        max_length=16,
                    ),
                ),
                ("content", models.TextField()),
                ("path", models.CharField(default="/", max_length=2048)),
                ("browser", models.CharField(blank=True, default="", max_length=500)),
                ("module", models.CharField(default="plane", max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In progress"),
                            ("done", "Done"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=128)),
                ("payload_hash", models.CharField(max_length=64)),
                ("legacy_feedback_id", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "org_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="research_feedbacks",
                        to="db.orgunit",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="research_feedbacks",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Research Feedback",
                "verbose_name_plural": "Research Feedback",
                "db_table": "research_feedbacks",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ResearchFeedbackScreenshot",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("position", models.PositiveSmallIntegerField(default=0)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="research_feedback_screenshots",
                        to="db.fileasset",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screenshots",
                        to="db.researchfeedback",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Research Feedback Screenshot",
                "verbose_name_plural": "Research Feedback Screenshots",
                "db_table": "research_feedback_screenshots",
                "ordering": ("position", "created_at"),
            },
        ),
        migrations.AddIndex(
            model_name="researchfeedback",
            index=models.Index(fields=["workspace", "created_at"], name="rsch_fb_ws_created_idx"),
        ),
        migrations.AddIndex(
            model_name="researchfeedback",
            index=models.Index(
                fields=["workspace", "org_unit", "status", "created_at"], name="rsch_fb_ws_org_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="researchfeedback",
            index=models.Index(fields=["workspace", "created_by", "created_at"], name="rsch_fb_ws_user_idx"),
        ),
        migrations.AddConstraint(
            model_name="researchfeedback",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("workspace", "created_by", "idempotency_key"),
                name="rsch_fb_uq_idempotency",
            ),
        ),
        migrations.AddConstraint(
            model_name="researchfeedback",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True), ("legacy_feedback_id__isnull", False)),
                fields=("workspace", "legacy_feedback_id"),
                name="rsch_fb_uq_legacy",
            ),
        ),
        migrations.AddIndex(
            model_name="researchfeedbackscreenshot",
            index=models.Index(fields=["feedback", "position"], name="rsch_fb_shot_feedback_idx"),
        ),
        migrations.AddConstraint(
            model_name="researchfeedbackscreenshot",
            constraint=models.UniqueConstraint(fields=("feedback", "asset"), name="rsch_fb_shot_uq_asset"),
        ),
    ]
